# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature_monitor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temperature_monitor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x19temperature_monitor.proto\"\x07\n\x05\x45mpty\"\x1e\n\x0bTemperature\x12\x0f\n\x07\x63\x65lsius\x18\x01 \x01(\x01\"\x17\n\x04Time\x12\x0f\n\x07seconds\x18\x01 \x01(\x01\"\"\n\x06MinMax\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x32\xb2\x01\n\x12TemperatureMonitor\x12,\n\x12\x43urrentTemperature\x12\x06.Empty\x1a\x0c.Temperature\"\x00\x12\'\n\x0cTemperatures\x12\x05.Time\x1a\x0c.Temperature\"\x00\x30\x01\x12&\n\x11MinMaxTemperature\x12\x06.Empty\x1a\x07.MinMax\"\x00\x12\x1d\n\nStressTest\x12\x05.Time\x1a\x06.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=36,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='celsius', full_name='Temperature.celsius', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=68,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='Time.seconds', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=93,
)


_MINMAX = _descriptor.Descriptor(
  name='MinMax',
  full_name='MinMax',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min', full_name='MinMax.min', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='MinMax.max', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['MinMax'] = _MINMAX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'temperature_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'temperature_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Temperature)
  })
_sym_db.RegisterMessage(Temperature)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'temperature_monitor_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

MinMax = _reflection.GeneratedProtocolMessageType('MinMax', (_message.Message,), {
  'DESCRIPTOR' : _MINMAX,
  '__module__' : 'temperature_monitor_pb2'
  # @@protoc_insertion_point(class_scope:MinMax)
  })
_sym_db.RegisterMessage(MinMax)



_TEMPERATUREMONITOR = _descriptor.ServiceDescriptor(
  name='TemperatureMonitor',
  full_name='TemperatureMonitor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=132,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='CurrentTemperature',
    full_name='TemperatureMonitor.CurrentTemperature',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TEMPERATURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Temperatures',
    full_name='TemperatureMonitor.Temperatures',
    index=1,
    containing_service=None,
    input_type=_TIME,
    output_type=_TEMPERATURE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MinMaxTemperature',
    full_name='TemperatureMonitor.MinMaxTemperature',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MINMAX,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StressTest',
    full_name='TemperatureMonitor.StressTest',
    index=3,
    containing_service=None,
    input_type=_TIME,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATUREMONITOR)

DESCRIPTOR.services_by_name['TemperatureMonitor'] = _TEMPERATUREMONITOR

# @@protoc_insertion_point(module_scope)
